DugisGuideViewer:RegisterGuide("Midsummer Festival Outland (60+)", nil, "Horde", "D", function() 
return [[
AAA

KJ^kr^iQf`hObnrfobayKyArbqlqebrkfnrbk^qroblcqebJfaprjjbobsbkq)ArdfpDrfabSfbtboWfp`roobkqivrk^_ibql^rqlj^qf`^iivabqb`qqebnrbpq^kavlrtfiikbbaqlqf`hqeb`ljmibqbanrbpqj^kr^iiv+Tb^obtlohfkdlk^plirqflky
OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqvy
>ElkloqebCi^jb%Qbolhh^oClobpq&yKyPqlkb_ob^hboElia%2/)10&yyWyQbolhh^oClobpqyyNFAy..525yyBy
>Abpb`o^qbqefpCfob%Qbolhh^oClobpq&yKy>iibof^kPqolkdelia%22)22&yyWyQbolhh^oClobpqyNFAy..421yyBy
>ElkloqebCi^jb%Pe^altjllkS^iibv&yKyPe^altjllkSfii^db%00)0-&yyWyPe^altjllkS^iibvyyNFAy..522yyBy
>Abpb`o^qbqefpCfob%Pe^altjllkS^iibv&yKyTfiae^jjboPqolkdelia%1-)22&yyWyPe^altjllkS^iibvyyNFAy..42/yyBy
>ElkloqebCi^jb%K^do^ka&yKyD^o^a^o%2.)01&yyWyK^do^kayyNFAy..521yyBy
>Abpb`o^qbqefpCfob%K^do^ka&yKyQbi^^o%2-)4-&yyWyK^do^kayyNFAy..42-yyBy
>ElkloqebCi^jb%W^kd^oj^ope&yKyW^_o^$Gfk%03)2/&yyWyW^kd^oj^opeyyNFAy..530yyBy
>Abpb`o^qbqefpCfob%W^kd^oj^ope&yKyQbiobalo%36)2/&yyWyW^kd^oj^opeyyNFAy..425yyBy
>ElkloqebCi^jb%EbiicfobMbkfkpri^&yKyQeo^iij^o%24)1/&yyWyEbiicfobMbkfkpri^yyNFAy..52.yyBy
>Abpb`o^qbqefpCfob%EbiicfobMbkfkpri^&yKyElkloElia%3/)25&yyWyEbiicfobMbkfkpri^yyNFAy..414yyBy
>ElkloqebCi^jb%?i^ab$pBadbJlrkq^fkp&yKyQerkaboiloaPqolkdelia%2-)26&yyWy?i^ab$pBadbJlrkq^fkpyyNFAy..510yyBy
>Abpb`o^qbqefpCfob%?i^ab$pBadbJlrkq^fkp&yKyPvis^k^^o%1/)33&yyWy?i^ab$pBadbJlrkq^fkpyyNFAy..403yyBy
>Abpb`o^qbqefpCfob%Kbqebopqloj&yKy>ob^2/%0.)30&yyWyKbqebopqlojyyNFAy..426yyBy
>ElkloqebCi^jb%Kbqebopqloj&yKy>ob^2/%0/)35&yyWyKbqebopqlojyyNFAy..502yyBy
KDrfab@ljmibqb

]]
end)
