DugisGuideViewer:RegisterGuide("Midsummer Festival Azeroth (50+)", nil, "Horde", "D", function() 
return [[
AAA

KJ^kr^iQf`hObnrfobayKyArbqlqebrkfnrbk^qroblcqebJfaprjjbobsbkq)ArdfpDrfabSfbtboWfp`roobkqivrk^_ibql^rqlj^qf`^iivabqb`qqebnrbpq^kavlrtfiikbbaqlqf`hqeb`ljmibqbanrbpqj^kr^iiv+Tb^obtlohfkdlk^plirqflky
OQerkabo?irccyKy?bdfk^qQerkabo?irccy

>ElkloqebCi^jb%?illaellcSfii^db&yKyJridlob%2.)3-&yyWyJridlobyyNFAy..52/yyBy
C?o^`hbkt^iiSfii^dbyKyCivcolj@^jmQro^glLjrp^Qerkabopqloj%11+1)26+.&yyWyQeb?^oobkpy
>ElkloqebCi^jb%?o^`hbkt^iiSfii^db&yKyArpqt^iiltJ^ope%00)0-&yyWyArpqt^iiltJ^opeyyNFAy..514yyBy
>Abpb`o^qbqefpCfob%Qebo^jlobFpib&yKyArpqt^iiltJ^ope%3/)1-&yyWyArpqt^iiltJ^opeyyNFAy..411yyBy

CCobbtfkaMlpqyKyCivqlCobbtfkaMlpq)Pe^oaf%02+3)0.+6&yyWyArpqt^iiltJ^opey

>ElkloqebCi^jb%CobbtfkaMlpq&yKyQelrp^kaKbbaibp%1.)2/&yyWyQelrp^kaKbbaibpyyNFAy..53.yyBy

CD^adbqw^kyKyCivqlD^adbqw^k)Kvpb%12+.)16+.&yyWyQelrp^kaKbbaibpy

>ElkloqebCi^jb%D^adbqw^k&yKyQ^k^ofp%16)/4&yyWyQ^k^ofpyyNFAy..505yyBy
>Abpb`o^qbqefpCfob%D^adbqw^k&yKyQ^k^ofp%2/)/6&yyWyQ^k^ofpyyNFAy..43/yyBy

C@bk^oflkEliayKyCivql@bk^oflkElia)%2.+3)/2+1&yyWyQ^k^ofpy

>ElkloqebCi^jb%@bk^oflkElia&yKyPfifqerp%13)11&yyWyPfifqerpyyNFAy..503yyBy
>Abpb`o^qbqefpCfob%@bk^oflkElia&yKyPfifqerp%24)01&yyWyPfifqerpyyNFAy..43-yyBy

C@^jmJlg^`ebyKyCivqlCbo^i^p)OrkhTfkq^jbo%15+4)03+4&yyWyPfifqerpy
>ElkloqebCi^jb%@^jmJlg^`eb&yKyCbo^i^p%4/)14&yyWyCbo^i^pyyNFAy..516yyBy
KQ^hbqeb?l^qqlCb^qebojllkyKyRpbqeb_l^q^q%10+1)1/+4&yyWyCbo^i^py

>Abpb`o^qbqefpCfob%Cb^qebojllkPqolkdelia&yKyCbo^i^p%/5)11&yyNFAy..413yyWyCbo^i^pyyBy

OAbpli^`byKyOrkqlAbpli^`b%1/+2)64&yyWyAbpli^`by

>ElkloqebCi^jb%Pe^altmobvSfii^db&yKyAbpli^`b%/3)43&yyWyAbpli^`byyNFAy..512yyBy
>Abpb`o^qbqefpCfob%Kfgbi$pMlfkq&yKyAbpli^`b%32).4&yyWyAbpli^`byyNFAy..41.yyBy

OPqlkbq^ilkJlrkq^fkpyKyOrkqlPqlkbq^ilkJlrkq^fkp%0-)41&yyWyPqlkbq^ilkJlrkq^fkpy

>ElkloqebCi^jb%PrkOl`hObqob^q&yKyPqlkbq^ilkJlrkq^fkp%2-)3-&yyWyPqlkbq^ilkJlrkq^fkpyyNFAy..523yyBy

C@olppol^apyKyCivql@olppol^ap)Qe^oj%12+.)26+6&yyWyPqlkbq^ilkJlrkq^fkpy

>ElkloqebCi^jb%@olppol^ap&yKyQeb?^oobkp%2/)/5&yyWyQeb?^oobkpyyNFAy..526yyBy
>ElkloqebCi^jb%O^wloEfii&yKyQeb?^oobkp%2/)14&yyWyArolq^oyyNFAy..513yyBy

_?llqv?^vyKyDlqlO^q`ebq^kaq^hbqeb_l^qql?llqv?^v%30+4)05+3&yyWyQeb?^oobkpy

>ElkloqebCi^jb%?llqv?^v&yKyPqo^kdibqelokS^ib%0/)42&yyWyPqo^kdibqelokS^ibyyNFAy..504yyBy
>Abpb`o^qbqefpCfob%?llqv?^v&yKyPqo^kdibqelokS^ib%00)40&yyWyPqo^kdibqelokS^ibyyNFAy..43.yyBy

CPt^jmlcPlooltpyKyCivqlPt^jmlcPlooltp)Of`hib%/3+6)44+.&yyWyPqo^kdibqelokS^iby

>ElkloqebCi^jb%Pqlk^oa&yKyPt^jmlcPlooltp%14)14&yyWyPt^jmlcPlooltpyyNFAy..524yyBy
O?i^pqbaI^kapyKyOrkql?i^pqbaI^kap%00+1)4/+0&yyWyPt^jmlcPlooltpy
>Abpb`o^qbqefpCfob%Kbqebod^oabHbbm&yKy?i^pqbaI^kap%25).4&yyWy?i^pqbaI^kapyyNFAy..404yyBy
OArphtllayKyOrkqlArphtlla%53)1-&yyWyArphtllay
>Abpb`o^qbqefpCfob%A^ohpefob&yKyArphtlla%41)2.&yyWyArphtllayyNFAy..410yyBy
OTbpqc^iiyKyOrkqlTbpqc^ii%32+0)30&yyWyTbpqc^iiy
>Abpb`o^qbqefpCfob%PbkqfkbiEfiiyKyTbpqc^ii%23)21&yyWyTbpqc^iiyyNFAy..25.yyBy
OBitvkkClobpqyKyOrkqlBitvkkClobpq%//)5-&yyWyBitvkkClobpqy
>Abpb`o^qbqefpCfob%Dliapefob&yKyBitvkkClobpq%10)32&yyWyBitvkkClobpqyyNFAy..412yyBy
KPqb^iXCi^jblcPqlojtfkaZyKyBfqebopkb^hfkpfablogrpqorkfktfqevlrojlrkq%2-)4/&yyIy/0.50yyWyPqlojtfka@fqvy
>Pqb^ifkdPqlojtfka$pCi^jbyRy/0.50yyLyyNFAy600-y
OObaofadbJlrkq^fkpyKyOrkqlObaofadbJlrkq^fkp%5+6)4.+6&yyWyObaofadbJlrkq^fkpy
>Abpb`o^qbqefpCfob%I^hbpefob&yKyObaofadbJlrkq^fkp%/1)26&yyWyObaofadbJlrkq^fkpyyNFAy..42.yyBy
O?rokfkdPqbmmbpyKyOrkql?rokfkdPqbmmbp%12+4)/+3&yyWy?rokfkdPqbmmbpy
>Abpb`o^qbqefpCfob%Jlod^k$pSfdfi&yKy?rokfkdPqbmmbp%5-)3/&yyWy?rokfkdPqbmmbpyyNFAy..406yyBy
>ElkloqebCi^jb%Ci^jb@obpq&yKy?rokfkdPqbmmbp%3/)/6&yyWy?rokfkdPqbmmbpyyNFAy..511yyBy
CH^od^qeyKyCivqlH^od^qe)S^edorh%32+4)/1+/&yyWy?rokfkdPqbmmbpy
>ElkloqebCi^jb%H^od^qe&yKy?^ai^kap%1)16&yyWy?^ai^kapyyNFAy..51/yyBy
OIl`eJla^kyKyOrkqlIl`eJlka^k%14)5-&yyWyIl`eJla^ky
>Abpb`o^qbqefpCfob%Qebip^j^o&yKyIl`eJla^k%0/)1-&yyWyIl`eJla^kyyNFAy..416yyBy
OArkJloldeyKyOrkqlArkJlolde%54+/)2/+5&yWyArkJloldey
>Abpb`o^qbqefpCfob%He^o^klp&yKy%13)13&yyWyArkJloldeyyNFAy..41/yyBy
KPqb^iXCi^jblcFolkclodbZyKyBfqebopkb^hfkpfablogrpqorkfktfqevlrojlrkq%32)/1&yyIy/0.50yyWyFolkclodby
>Pqb^ifkdFolkclodb$pCi^jbyRy/0.50yyNFAy600.yyLy
OIl`eJla^kyKyOrkqlIl`eJlka^k%.6).4+0&yyWyIl`eJla^ky
OTbqi^kapyKyOrkqlTbqi^kap%20+4)4/+1&yyWyTbqi^kapy
>Abpb`o^qbqefpCfob%JbkbqefiE^o_lo&yKy%.0)14&yyWyTbqi^kapyyNFAy..424yyBy
O>o^qefEfdei^kapyKyOrkql>o^qefEfdei^kap%12)56&yyWy>o^qefEfdei^kapy
>Abpb`o^qbqefpCfob%ObcrdbMlfkq&yKy%2-)11&yyWy>o^qefEfdei^kapyyNFAy..40/yyBy
>ElkloqebCi^jb%E^jjboc^ii&yKy%41)1.&yyWy>o^qefEfdei^kapyyNFAy..51-yyBy
CQ^oobkJfiiyKyCivqlQ^oobkJfii)Roa^%40)0/+4&yyWy>o^qefEfdei^kapy
>ElkloqebCi^jb%Q^oobkJfii&yKy%25)/2&yyWyEfiip_o^aCllqefiipyyNFAy..520yyBy
>Abpb`o^qbqefpCfob%Plrqepelob&yKy%2-)13&yyWyEfiip_o^aCllqefiipyyNFAy..415yyBy

CPfisbomfkbClobpqyKyCivqlPfisbomfkbClobpq)W^ofpb%3-+.).5+3&vlrorkqebobfcvlralk$qe^sbqebcifdeqmlfkqyyWyEfiip_o^aCllqefiipy
>ElkloqebCi^jb%QebPbmri`ebo&yKyPfisbomfkbClobpq%16)05&yyWyPfisbomfkbClobpqyyNFAy..251yyBy

CRkabo`fqvyKyCivqlRkabo`fqv)H^olpO^wlh%12+3)1/+3&yyWyPfisbomfkbClobpqy
OPfisbojllk@fqvyKyRpbqebMloq^i^q%22)6+6&qlqbibmloqqlPfisbojllk@fqv^kabufqqlBsboplkdTllapyyWyRkabo`fqvy
>ElkloqebCi^jb%KloqeP^k`qrj&yKyBsboplkdTllap%13)2-&yyWyBsboplkdTllapyyNFAy..515yyBy
>ElkloqebCi^jb%Qo^knrfifbk&yKyDelpqi^kap%13)/3&yyWyDelpqi^kapyyNFAy..52-yyBy

CObs^kqrphSfii^dbyKyCivqlObs^kqrphSfii^db)Phvj^pqboPrktfkd%12+1)0-+2&yyWyDelpqi^kapy
>ElkloqebCi^jb%Obs^kqrphSfii^db&yKyQebEfkqboi^kap%43)41&yyWyQebEfkqboi^kapyyNFAy..53-yyBy
>Abpb`o^qbqefpCfob%>bofbMb^h&yKyQebEfkqboi^kap%.1)2-&yyWyQebEfkqboi^kapyyNFAy..422yyBy

CQ^oobkJfiiyKyCivqlQ^oobkJfii)Dloh^p%5.+4)5.+5&yyWyQebEfkqboi^kapy
>Abpb`o^qbqefpCfob%@efiitfka@^jm&yKyTbpqbokMi^drbi^kap%10)5/&yyWyTbpqbokMi^drbi^kapyyNFAy..423yyBy
>ElkloqebCi^jb%?ofii&yKy%24)2/&yyWyQfofpc^iDi^abpyyNFAy..53/yyBy

CArolq^oyKyQ^hbqebWbmmbifkqlArolq^o%3-+4)25+5&yyWyQfofpc^iDi^abpy

CBsboillhyKyCivqlBsboillh)Alo^p%12+.)03+6&yyWyLodofjj^oy
>ElkloqebCi^jb%Bsboillh&yKyTfkqbopmofkd%26)02&yyWyTfkqbopmofkdyyNFAy..506yyBy
>Abpb`o^qbqefpCfob%Bsboillh&yKyTfkqbopmofkd%3/)02&yyWyTfkqbopmofkdyyNFAy..430yyBy

CPmifkqboqobbMlpqyKyCivqlPmifkqboqobbMlpq)Vrdobh%3-+2)03+0&yyWyTfkqbopmofkdy
>ElkloqebCi^jb%PmifkqboqobbMlpq&yKy>pebks^ib%4-)36&yyWy>pebks^ibyyNFAy..51.yyBy
>Abpb`o^qbqefpCfob%>pqo^k^^o&yKy>pebks^ib%05)21&yyWy>pebks^ibyyNFAy..401yyBy

OA^ohpelobyKyOrkqlA^ohpelob%10)61&yyWyA^ohpeloby
>Abpb`o^qbqefpCfob%>r_boafkb&yKyA^ohpelob%04)13&yyWyA^ohpelobyyNFAy..41-yyBy

_>wrobjvpqFpibyKyQ^hbqeb?l^qql>wrobjvpqFpib)%0-+4)1.&yyWyA^ohpeloby
KPqb^iXCi^jblcBula^oZyKyBfqebopkb^hfkpfablogrpqorkfktfqevlrojlrkq%1.)/1&yyIy02236yyWyQebBula^oy
>Pqb^ifkdqebBula^o$pCi^jbyRy02236yyNFAy..600y
>Abpb`o^qbqefpCfob%>wrobT^q`e&yKy>wrobjvpqFpib%11)20&yyWy>wrobjvpqFpibyyNFAy..402yyBy
>Abpb`o^qbqefpCfob%?illaT^q`e&yKy?illajvpqFpib%22)36&yyWy?illajvpqFpibyyNFAy..405yyBy

_>r_boafkbyKyQ^hbqeb_l^q_^`hql>r_boafkb)%/.+5)20+/&yyWy>wrobjvpqFpiby
_Qbiao^ppfiyKyQ^hbqebkloqepfab_l^qqlQbiao^ppfi%00)1-+/&yyWyA^ohpeloby
KPqb^iXCi^jblcA^ok^pprpZyKyBfqebopkb^hfkpfablogrpqorkfktfqevlrojlrkq%22)6.&yyIy/0.51yyWyA^ok^pprpy
>Pqb^ifkdA^ok^pprp$pCi^jbyRy/0.51yyNFAy600/y
OA^ok^pprpyKyOrkqeolrdeqebmloq^iqlA^ok^pprp%22+5)56+1&yyWyQbiao^ppfiy
>Abpb`o^qbqefpCfob%Ali^k^^o&yKyQbiao^ppfi%22)3-&yyNFAy..420yyWyQbiao^ppfiyyBy
K>wbolqeDrfab@ljmibqb

]]
end)
